"""empty message

Revision ID: 0880e15683a7
Revises: 
Create Date: 2025-03-06 10:33:14.272039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '0880e15683a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemRequests',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('requested_by_id', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('requested_by', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('item_group_code', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('qualimed_bu', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('u_bb_code', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('item_name', sa.NVARCHAR(length=250), nullable=True),
    sa.Column('generic_name', sa.NVARCHAR(length=250), nullable=True),
    sa.Column('measurement', sa.NVARCHAR(length=250), nullable=True),
    sa.Column('uom_code', sa.NVARCHAR(length=250), nullable=True),
    sa.Column('brand_name', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('mfg', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('other_descriptors', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('purchaseable', sa.Boolean(), nullable=True),
    sa.Column('sellable', sa.Boolean(), nullable=True),
    sa.Column('inventory_item', sa.Boolean(), nullable=True),
    sa.Column('status', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemRequests')
    # ### end Alembic commands ###
