"""empty message

Revision ID: cbce033739cc
Revises: 
Create Date: 2025-02-28 08:33:31.803899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbce033739cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_requested', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by_id', sa.String(length=100), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('item_group_code', sa.Integer(), nullable=True),
    sa.Column('qualimed_bu', sa.String(length=100), nullable=True),
    sa.Column('u_bb_code', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=250), nullable=True),
    sa.Column('generic_name', sa.JSON(), nullable=True),
    sa.Column('measurement', sa.JSON(), nullable=True),
    sa.Column('uom_code', sa.JSON(), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('mfg', sa.String(length=100), nullable=True),
    sa.Column('other_descriptors', sa.String(length=100), nullable=True),
    sa.Column('purc_sell_item', sa.Boolean(), nullable=True),
    sa.Column('sell_item', sa.Boolean(), nullable=True),
    sa.Column('inventory_item', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_group',
    sa.Column('item_group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_group_code', sa.String(length=100), nullable=True),
    sa.Column('item_group_desc', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('item_group_id')
    )
    op.create_table('unit_of_measure',
    sa.Column('uom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uom_code', sa.String(length=100), nullable=True),
    sa.Column('uom_desc', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_of_measure')
    op.drop_table('item_group')
    op.drop_table('item')
    op.drop_table('account')
    # ### end Alembic commands ###
